### ISSUE TITLE
Single Line Comments with quotes have unexpected behavior 

### ISSUE THREAD

**Issue by penang** [dvryaboy/piglatin-mode#1]
Balanced quotes in a single line comment affects that particular line's highlighting.
e.g . -- "License"); you may not use this file except in compliance with the License.

Unbalanced quotes in a single line comment affects the rest of the file's highlighting (or till it finds a subsequent quote to balance).
e.g. -- "License); you may not use this file except in compliance with the License.

**Comment by dvryaboy** [comment]
Hi penang,
I'm not actively maintaining this feature anymore, but feel free to send a pull request, I'd be happy to integrate it.
